### ISSUE TITLE
Weird result

### ISSUE THREAD

**Issue by Ralle** [Kanma/BLPConverter#10]
I am getting a really weird result from conversion. Here is the input:
[Wc3 Trigger Editor.zip](https://github.com/Kanma/BLPConverter/files/1099617/Wc3.Trigger.Editor.zip)

And the output is expected to look like this:
![actions](https://user-images.githubusercontent.com/467309/27508171-f81bad36-58df-11e7-8995-a309e878d38e.gif)
![cond](https://user-images.githubusercontent.com/467309/27508172-f81e0c48-58df-11e7-9fbb-b3956b892d36.gif)
![events](https://user-images.githubusercontent.com/467309/27508173-f823b17a-58df-11e7-9e8b-cd4a5a33fd6d.gif)

And this is what I am getting (note, they are white, you must right click and inspect them to see them properly):
![editor-triggeraction](https://user-images.githubusercontent.com/467309/27508187-20999868-58e0-11e7-93ce-a83e143da841.png)
![editor-triggercondition](https://user-images.githubusercontent.com/467309/27508186-20950e9c-58e0-11e7-8911-05a79160de59.png)
![editor-triggerevent](https://user-images.githubusercontent.com/467309/27508188-20ab2056-58e0-11e7-9f41-c8ffe993b7cf.png)

Please advice.

**Comment by Kanma** [comment]
It should be fixed now.

I don't remember why I handled the alpha differently for alphaEncoding == 3 and alphaEncoding == 4. I didn't found any information on the internet about the difference between the two. I confirmed using other files that not inverting the alpha in either case was the correct behavior.

**Comment by Ralle** [comment]
Oh! Excellent. I will recompile and try out the new version soon.
