### ISSUE TITLE
Corrupt BLP or error?

### ISSUE THREAD

**Issue by Ralle** [Kanma/BLPConverter#6]
Hello. I have a single BLP that does not convert. Could you take a look at it and tell me if it's just this BLP that's broken or if there is an error in the code?
[SlimeSkinBlue.blp.zip](https://github.com/Kanma/BLPConverter/files/84027/SlimeSkinBlue.blp.zip)

Thanks!

**Comment by Kanma** [comment]
Hello

I think it might be a problem with the BLP file.

The conversion fails when an attempt is made to decode the JPEG image stored inside the BLP file (at [blp.cpp:297](https://github.com/Kanma/BLPConverter/blob/master/blp.cpp#L297)).

If you put the following lines at, say, line 295, a file called *image.jpg* will be created containing the bytes extracted from the BLP file that are supposed to be a JPEG image:

    FILE* pFile = fopen("image.jpg", "wb");
    fwrite((void*) pSrcBuffer, pInfos->jpeg.headerSize + size, 1, pFile);
    fclose(pFile);

In this case, *image.jpg* is a 51KB file that doesn't look like a correct JPEG image: its dimensions are reported to be 0x0 pixels. I don't know if it is the only error in the file.

**Comment by Ralle** [comment]
Okay. Thank you very much for taking a look :).
